#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import daqd, config
from copy import deepcopy
from time import sleep
import argparse
import os
import subprocess
import ROOT
import sys
import math
from datetime import datetime
from collections import OrderedDict

sys.path.append("/home/cmsdaq/Programs/Lab5015Utils/")
#from Lab5015_utils import Keithley2450
from Lab5015_utils import KeithleyDMM6500

parser = argparse.ArgumentParser(description='Acquire SiPM IV scan')
parser.add_argument("--config", type=str, required=True, help="Configuration file")
parser.add_argument("--bvMin", type=str, dest="bvMin", required=True, help="starting bv")
parser.add_argument("--bvMax", type=str, dest="bvMax", required=True, help="ending bv")
parser.add_argument("--asic", type=int, required=True, help="ASIC ID")
parser.add_argument("--aldo", type=str, dest="aldo", required=True, help="which ALDO")
parser.add_argument("--ch", type=str, dest="ch", required=True, help="which channel of the keithley to measure")
parser.add_argument("--nMeas", type=str, dest="nMeas", required=False, help="number of measurements to average")
parser.add_argument("--label", type=str, dest="label", required=True, help="label")
parser.add_argument("--verbose", dest="verb", action="store_true", help="set to true to display output and plots, otherwise just save to root file")
parser.add_argument("--plot", dest="plot", action="store_true", help="set to true to display plots, otherwise just save to root file")
parser.add_argument("--fast", dest="fast", action="store_true", help="perform fast IV scan") 
parser.add_argument("--dacStep", type=int, required=False, help="step in dac units", default=1)



#------------------------
# parsing input arguments
args = parser.parse_args()
verbose = False
if args.verb:
    verbose = True


#---------------------------------
# connect and configure multimeter
mykey = KeithleyDMM6500()                                                                                                                                                                                                                                                                                                                                                 
mykey.closeChannel(int(args.ch))


#-----------------------------
# load configuration from file
mask = config.LOAD_ALL
# if args.mode != "mixed":
#         mask ^= config.LOAD_QDCMODE_MAP
mask ^= config.LOAD_QDCMODE_MAP
systemConfig = config.ConfigFromFile(args.config, loadMask=mask)

daqd = daqd.Connection()
daqd.initializeSystem()
systemConfig.loadToHardware(daqd, bias_enable=config.APPLY_BIAS_OFF)

asicsConfig = daqd.getAsicsConfig()
activeAsics = daqd.getActiveAsics()

if len(activeAsics) == 0:
    print ("no active ASICs found. Exiting...")
    exit()
    
asicsConfig0 = deepcopy(asicsConfig)
cfg = deepcopy(asicsConfig0)

for portID, slaveID, chipID in activeAsics:
    if chipID%2 is not 0:
        continue
        
    ac = cfg[(portID, slaveID, chipID)]
    gc = (cfg[(portID, slaveID, chipID)]).globalConfig
    gc.setValue("c_aldo_en", 0b00)
    daqd.setAsicsConfig(cfg)
    sleep(5.)
    stdout = mykey.read()
    sleep(2)
    
    print( "ALDO off   I: %f uA" % (abs(stdout)*1E06/10.))


#--------------
# define graphs
g_I = OrderedDict()
g_IV = ROOT.TGraph()
g_dlogIdV = ROOT.TGraph()


logfolder = '../log_IV/'
if not os.path.exists(logfolder):
    os.mkdir(logfolder)
    print logfolder


#--------
# ov scan
for portID, slaveID, chipID in activeAsics:
        if chipID%2 is not 0:
                continue
        if int(chipID) != args.asic:
            continue
        
        print(portID,slaveID,chipID)
        
        ac = cfg[(portID, slaveID, chipID)]
        for dac in range(0,256,args.dacStep):
                voltA, voltB = systemConfig.mapALDODACToVoltage((portID, slaveID, chipID),dac)
                volt = 0.
                
                if args.aldo is "A":
                    volt = float(voltA)                
                if args.aldo is "B":
                    volt = float(voltB)
                if volt < float(args.bvMin):
                    continue
                if volt > float(args.bvMax):
                    break
                
                g_I[volt] = ROOT.TGraph()
                
                gc = (cfg[(portID, slaveID, chipID)]).globalConfig
                if args.aldo is "A":
                    gc.setValue("c_aldo_en", 0b10)
                    gc.setValue("Valdo_A_DAC", dac)

                if args.aldo is "B":
                    gc.setValue("c_aldo_en", 0b01)
                    gc.setValue("Valdo_B_DAC", dac)

                daqd.setAsicsConfig(cfg)
                
                sleep(0.25)
                
                curr  = 0.
                vMeas = 0.
                nMeas = 1
                curr_list = []
                
                start_curr = 0.
                start_volt = 0.
                if (not args.fast):
                    stdout = mykey.read()
                    start_volt = abs(stdout)
                    start_curr = start_volt*1E06/10./1000. #to have it in mA
                    curr_list.append(start_curr)
                
                if args.nMeas:
                    nMeas = int(args.nMeas)
                #if not args.fast:
                #    nMeas = 1 + int((start_curr/16.)*10)                    
                #    print(start_curr,nMeas)
                
                it = 0
                for _ in range(nMeas):
                        sleep(0.25)
                        stdout = mykey.read()
                        this_volt = abs(stdout)
                        this_curr = this_volt*1E06/10.

                        if verbose:
                            print ("dac: %3d   V_set: %6.3f V   V_meas: %f V -->  I: %f uA" % (int(dac),volt,this_volt,this_curr))
                        g_I[volt].SetPoint(g_I[volt].GetN(),g_I[volt].GetN(),this_curr)
                        
                        if it >= 0:
                                curr = curr + this_curr
                                vMeas = vMeas + this_volt
                        it += 1
                        # last5ave = 0
                        # print("nMeas = %f"%len(curr_list))
                        # if (len(curr_list)>7):
                        #     for i in range(5):
                        #         last5ave = last5ave + curr_list[len(curr_list)-i]
                        #         print("last5ave = %f, this_curr = %f"%(last5ave, this_curr))

                        #     if (this_curr>last5ave): 
                        #         break

                        # curr_list.append(this_curr)
                
                curr  = curr  / nMeas
                vMeas = vMeas / nMeas
                g_IV.SetPoint(g_IV.GetN(),volt, curr)
                print( "===> dac: %3d   V_set: %6.3f V_meas: %6.3f V -->  I: %f uA" % (int(dac),volt,vMeas,curr))


#-------------------------
# switch off bias voltages

for portID, slaveID, chipID in activeAsics:
        if chipID%2 is not 0:
                continue
        gc = (cfg[(portID, slaveID, chipID)]).globalConfig
        gc.setValue("c_aldo_en", 0b00)
daqd.setAsicsConfig(cfg)                                                                                                                                           


#---------
# plotting
for point in range(1,g_IV.GetN()):
    x1 = g_IV.GetPointX(point-1)
    x2 = g_IV.GetPointX(point)
    y1 = g_IV.GetPointY(point-1)
    y2 = g_IV.GetPointY(point)
    if x2 != x1:
        g_dlogIdV.SetPoint(g_dlogIdV.GetN(),0.5*(x1+x2),(math.log(y2)-math.log(y1))/(x2-x1))
    
if args.plot:
    c2 = ROOT.TCanvas("c2","c2",500,500)
    g_IV.SetTitle("I vs volt;volt [V]; I [#muA]")
    g_IV.Draw("APL")
    
    c3 = ROOT.TCanvas("c3","c3",500,500)
    g_dlogIdV.SetTitle("dlogIdV vs volt;volt [V]; #DeltalogI/#DeltaV [#muA/V]")
    g_dlogIdV.Draw("APL")
    
    raw_input("ok?")

now = datetime.now()
this_time = now.strftime('%Y-%m-%d_%H:%M:%S')

logfile = '%s/logIV_%s_ASIC%d_ALDO%s_time_%s'%(logfolder,args.label,args.asic,args.aldo,this_time)+'.root'
print('saving data to: %s' % logfile)

outFile = ROOT.TFile(logfile,"RECREATE")
outFile.cd()
for volt in g_I.keys():
    g_I[volt].SetName('g_I_bv%.2f'%volt)
    g_I[volt].Write()
g_IV.SetName("g_IV")
g_IV.Write()
g_dlogIdV.SetName("g_dlogIdV")
g_dlogIdV.Write()
outFile.Write()
outFile.Close()
