#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import tester_controller, config, spi, tofhir2b, tests
from copy import deepcopy
import argparse
import math
import time
import subprocess
import sys
import itertools
import bitarray
import os
import pandas as pd
import numpy as np
import termios
import tempfile


AUTO_BANDGAP_TRIM = True

def main(argv):
	parser = argparse.ArgumentParser(description='Test TOFHiR 2 BGA')
	parser.add_argument("-o", type=str, required=True, help="Output directory")
	parser.add_argument("-n", type=int, default=8, help="Number of BGA testers")
	parser.add_argument("--batch", action="store_true", help="Batch mode")
	args = parser.parse_args()
	
	## TEST CODE
	# Set to TRUE to make the BGA pick and place wait for user after each test
	enable_user_prompt = False
	
	if not args.batch:
		# Manual operation mode
		trimmed = raw_input("Have these ASICs been trimmed before? (Y/N)")
		if trimmed in [ 'y', 'Y' ]:
			do_bg_trim = False
		elif trimmed in [ 'n', 'N' ]:
			do_bg_trim = True
		else:
			sys.stderr.write("Invalid answer.\n")
			return 1
			
	else:
		do_bg_trim = AUTO_BANDGAP_TRIM

	os.mkdir(args.o)

	conn = tester_controller.Connection()
	
	# Set the system to TOFHiR 2C mode
	conn.write_config_register(0, 0, 16, 0x0104, 0x0004)

	# Reset the aux MMCM
	conn.spi_master_execute(0, 0, 0x02, 4,
			16,
			1, 15,
			3, 4,
			0, 15,
			0, 15,
			[0x00, 0x00]
		);

	conn.set_uut_power(False)

	# Check that we have all expected testers
	n_testers = len(conn.get_testers().keys())
	if n_testers != args.n:
		sys.stderr.write("Expected %d testers, found %d\n" % (args.n, n_testers))
		exit(1)


	uut_failures = {}
	sockets = itertools.product(conn.get_testers().items(), [0, 1])
	sockets = [ (m,a,t) for ((p, s, m), t), a in sockets ]
	sockets = sorted(sockets)
	
	for m,a,t in sockets:
		uut_failures[m,a] = []

	for m,a,t in sockets:
		t.set_leds(a, 0b000)
	conn.set_uut_power(True)


	# ASICs which have been found to be in short circuit will have been powered down
	for m, a, t in sockets:
		uut_on = t.get_uut_on(a)
		if not uut_on:
			# This socket was turned off due to a short circuit
			uut_failures[m,a].append("SHORT CIRCUIT")
	
	do_tester_check(conn)
			
	# Check that ASIC current draw is within normal range (before initialization)
	uut_failures = merge_failures(uut_failures, tests.bga_check_current(conn, sockets, 0.020, 0.6, "AFTER POWER UP", os.path.join(args.o, "current_before_init.tsv")))
	sockets = disable_failed(sockets, uut_failures)
	
	# Check that ASICs react to RESET_N
	uut_failures = merge_failures(uut_failures, tests.bga_check_reset_n(conn, sockets))
	sockets = disable_failed(sockets, uut_failures)
	
	uut_failures = merge_failures(uut_failures, tests.bga_check_current(conn, sockets, 0.020, 0.1, "DURING RESET", os.path.join(args.o, "current_during_reset.tsv")))
	sockets = disable_failed(sockets, uut_failures)
	
	
	# Check that ASICs will perform basic communication
	uut_failures = merge_failures(uut_failures, tests.check_asic_communication(conn, sockets))
	sockets = disable_failed(sockets, uut_failures)
	
	# Check that ASIC current draw is within normal range (after initialization)
	uut_failures = merge_failures(uut_failures, tests.bga_check_current(conn, sockets, 0.35, 0.6, "AFTER INIT", os.path.join(args.o, "current_after_init.tsv")))
	sockets = disable_failed(sockets, uut_failures)
	
	do_tester_check(conn)

	# Trim bandgap (optional) and check bandgap value after trimming
	if do_bg_trim:
		tests.bga_do_bg_trim(conn, sockets)
	
	uut_failures = merge_failures(uut_failures, tests.bga_check_bg_trim(conn, sockets, os.path.join(args.o, "bandgap.tsv")))
	sockets = disable_failed(sockets, uut_failures)

	uut_failures = merge_failures(uut_failures, tests.check_itrim(conn, sockets, os.path.join(args.o, "itrim.tsv")))
	sockets = disable_failed(sockets, uut_failures)
	
	uut_failures = merge_failures(uut_failures, tests.bga_check_id(conn, sockets))
	sockets = disable_failed(sockets, uut_failures)

	uut_failures = merge_failures(uut_failures, tests.check_multiple_links(conn, sockets))
	sockets = disable_failed(sockets, uut_failures)

	# Write a list of active sockets up to this point to be used for reprocessing
	f = open("%s/reprocess_list.tsv" % args.o, "w")
	for m,a,t in sockets:
		f.write("%d\t%d\n" % (m, a))
	f.close()

	uut_failures = merge_failures(uut_failures, tests.check_rx_phase(conn, sockets, args.o))
	sockets = disable_failed(sockets, uut_failures)
	
	
	
	## Run stuff
	os.system("cp ../config.ini %s" % args.o)
	os.system("./make_simple_channel_map -o %s/map --port 0 --slave 0 --trigger-port 0" % args.o)
	os.system("./tester_read_dc --no-power-up | tee %s/dc.txt" % args.o)


	disc_range_list = { 0b01: "full", 0b10: "full" }
	qdc_att_list = { 0b111 : "full", 0b110: "fast", 0b011: "full" }
	xxtp_att = 0b011
	extp_amp_list = [ 0xFFFF ]
	fetp_amp_list = [ v for v in range(3, 32, 4) ]
	
	assert xxtp_att in qdc_att_list.keys()

	
	for disc_range, mode in disc_range_list.items():
		uut_failures = merge_failures(uut_failures, tests.check_discriminators(conn, sockets, disc_range, mode, args.o))
		
	uut_failures = merge_failures(uut_failures, tests.check_tdc(conn, sockets, "full", args.o))
	
	for att, mode in qdc_att_list.items():
		uut_failures = merge_failures(uut_failures, tests.check_qdc(conn, sockets, att, mode, args.o))
		
	uut_failures = merge_failures(uut_failures, tests.check_fetp_tres(conn, sockets, xxtp_att, args.o))
	uut_failures = merge_failures(uut_failures, tests.check_fetp_eres(conn, sockets, xxtp_att, args.o))

	uut_failures = merge_failures(uut_failures, tests.check_extp_tres(conn, sockets, xxtp_att, args.o))
	uut_failures = merge_failures(uut_failures, tests.check_extp_eres(conn, sockets, xxtp_att, args.o))
		

	uut_failures = merge_failures(uut_failures, tests.check_aldo(conn, sockets, 7, 1.0, args.o))


	results_file = open("%s/results.tsv" % args.o, "w")
	detailed_results_file = open("%s/detailed_results.tsv" % args.o, "w")
	
	for (m, a), failures in uut_failures.items():
		detailed_results_file.write("%d\t%d\t%s\n" % (m, a, ("\t").join(failures)))

		if failures == []:
			results_file.write("%d\t%d\tPASS\n" % (m, a))
		else:
			# TODO 
			# Actually fail ASICs when cut off limits are set
			results_file.write("%d\t%d\tPASS\n" % (m, a))
	
	detailed_results_file.close()
	results_file.close()
	

	print sockets
	print uut_failures
	
	# Test sucessfully complete
	conn.set_uut_power(False)

	if enable_user_prompt and args.batch:
		# When called by test_bga_auto 
		# instead of actually running a test just wait for user input
		# and return
		print "*** PRESS ENTER TO CONTINUE ***"
		a = raw_input()

		
	return 0


def merge_failures(a, b):
	c = {}
	
	# Sanity check
	# If we have a fail report for a previously unknown ASIC
	# it's most likely a bug in the code
	for k in b.keys():
		assert k in a.keys()
		
	for k in a.keys():
		c[k] = a[k]
		if b.has_key(k):
			a[k] += b[k]
	
	return c


def disable_failed(sockets, uut_failures):
	for m,a,t in sockets:
		if uut_failures[m,a] != []:
			t.set_uut_on(a, False)
		else:
			t.set_uut_on(a, True)

	result = [ (m,a,t) for m,a,t in sockets if t.get_uut_on(a) ]
	time.sleep(0.1)
	print "Still active sockets: ", [ (m, a) for m,a,t in result ]
	return result


def do_tester_check(conn):
	problems = False
	for (p,s,m),t in sorted(conn.get_testers().items()):
		tester_vin = t.get_tester_vin()
		
		if tester_vin < 1.6:
			print "Tester %d Vin %3.2f is LOW" % (m, tester_vin)
			problems = True
			
		if tester_vin > 2.5:			
			print "Tester %d Vin %3.2f is HIGH" % (m, tester_vin)
			problems = True
			
			
		for a in [0, 1]:
			# If the UUT has been disabled Vin should be ~0
			if t.get_uut_on(a) is False: continue
			
			uut_vin = t.get_uut_vin(a)
			
			if uut_vin < (1.2 * 0.98):
				print "Tester %d UUT %d Vin %3.2f is LOW" % (m, a, uut_vin)
				problems = True
				
			if uut_vin > (1.2 * 1.02):
				print "Tester %d UUT %d Vin %3.2f is HIGH" % (m, a, uut_vin)
				problems = True
	
	
	if problems:
		print "PROBLEMS FOUND IN TEST SYSTEM"
		exit(1)
	
	
	
if __name__ == '__main__':
	exit(main(sys.argv))
	
