#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import tester_controller, config, spi, tofhir2b, tests
from copy import deepcopy
import argparse
import math
import time
import subprocess
import sys
import itertools
import bitarray
import os
import pandas as pd
import numpy as np
import termios
import tempfile
from DS18B20_temperature_sensor import read_temperature_probe1, read_temperature_probe2


AUTO_BANDGAP_TRIM = True

def main(argv):
	parser = argparse.ArgumentParser(description='Test TOFHiR 2 FE')
	parser.add_argument("-o", type=str, required=True, help="Output directory")
	parser.add_argument("-n", type=int, default=8, help="Number of FE testers")
	args = parser.parse_args()
	
	os.mkdir(args.o)

	conn = tester_controller.Connection()
	
	# Attempt to set system mode to TOFHiR 2C
	conn.write_config_register(0, 0, 16, 0x0104, 0x0004)
	
	# Reset the aux MMCM
	conn.spi_master_execute(0, 0, 0x02, 4,
			16,
			1, 15,
			3, 4,
			0, 15,
			0, 15,
			[0x00, 0x00]
		);



	conn.set_uut_power(False)
	time.sleep(1.0)

	# Check that we have all expected testers
	n_testers = len(conn.get_testers().keys())
	if n_testers != args.n:
		sys.stderr.write("Expected %d testers, found %d\n" % (args.n, n_testers))
		exit(1)


	uut_failures = {}
	testers = [ (m,t) for (p,s,m),t in conn.get_testers().items() ]
	testers = sorted(testers)

	f1 = open("%s/list.txt" % args.o, "w")
	for m, t in testers:
		print "FE S/N for port %d?" % m
		termios.tcflush(sys.stdin, termios.TCIFLUSH)
		sn = raw_input()
		sn = sn.upper()
		f1.write("%d\t%s\n" % (m, sn))

		f2 = open("%s/SN_%s.txt" % (args.o, sn), "w")
		f2.write("%d\n" % m)
		f2.close()
	f1.close()
	
	for m,t in testers:
		uut_failures[m] = []
		

	conn.set_uut_power(True)
	for m,t in testers:
		uut_on = t.get_uut_power()
		if not uut_on:
			# This socket was turned off due to a short circuit
			uut_failures[m].append("SHORT CIRCUIT")
			
	do_tester_check(conn)

	uut_failures = merge_failures(uut_failures, tests.fe_check_current(conn, testers, 0.020, 0.2, "AFTER POWER UP", os.path.join(args.o, "current_after_power_up.tsv")))
	testers = disable_failed(testers, uut_failures)
	
	
	# Check that ASICs will perform basic communication
	uut_failures = merge_failures_MS(uut_failures, tests.check_asic_communication(conn, MS(testers)))
	testers = disable_failed(testers, uut_failures)
	
	# Check that ASIC current draw is within normal range (after initialization)
	uut_failures = merge_failures(uut_failures, tests.fe_check_current(conn, testers, 0.75, 0.85, "AFTER INIT", os.path.join(args.o, "current_after_init.tsv")))
	testers = disable_failed(testers, uut_failures)

	do_tester_check(conn)

	uut_failures = merge_failures_MS(uut_failures, tests.check_multiple_links(conn, MS(testers)))
	testers = disable_failed(testers, uut_failures)

	# Write a list of active testers up to this point to be used for reprocessing
	f = open("%s/reprocess_list.tsv" % args.o, "w")
	for m,t in testers:
		f.write("%d\n" % (m))
	f.close()

	uut_failures = merge_failures_MS(uut_failures, tests.check_itrim(conn, MS(testers), os.path.join(args.o, "itrim.tsv")))

	# Run test with bias load
	conn.set_48V_power(True)
	for m, t in testers: t.enable_bias_voltage_load(True)
	uut_failures = merge_failures_MS(uut_failures, tests.check_aldo(conn, MS(testers), 1, (220+5.11)/5.11, args.o, fe_mode=True))
	for m, t in testers: t.enable_bias_voltage_load(False)
	conn.set_48V_power(False)

	uut_failures = merge_failures(uut_failures, tests.check_aldo_fe(conn, testers, args.o))

	uut_failures = merge_failures(uut_failures, tests.check_pt1000(conn, testers, args.o))

	uut_failures = merge_failures(uut_failures, tests.check_tec(conn, testers, args.o))

	## Run stuff
	os.system("cp ../config.ini %s" % args.o)
	os.system("./make_simple_channel_map -o %s/map --port 0 --slave 0 --trigger-port 0" % args.o)
	os.system("./tester_read_dc --no-power-up | tee %s/dc.txt" % args.o)


	# Give the user the chance to abort before longer tests start
	if uut_failures != []:
		print "Some boards have failures"
		for m, s in uut_failures.items():
			print m, s

		print "Abort? (Y/N)"
		termios.tcflush(sys.stdin, termios.TCIFLUSH)
		abort = raw_input().upper()

		if abort == "Y":
			conn.set_uut_power(False)
			return 0




	uut_failures = merge_failures_MS(uut_failures, tests.check_rx_phase(conn, MS(testers), args.o, fe_mode=True))

	disc_range_list = { 0 : "full", 1: "full", 2: "full", 3: "full" }
	#qdc_att_list = { 0b111 : "full", 0b110: "fast", 0b011: "full" }
	qdc_att_list = dict([ ( att, "full") for att in range(8) ])
	xxtp_att = 0b011
	extp_amp_list = [ 0xFFFF ]
	fetp_amp_list = [ v for v in range(3, 32, 4) ]
	
	assert xxtp_att in qdc_att_list.keys()

	
	for disc_range, mode in disc_range_list.items():
		uut_failures = merge_failures_MS(uut_failures, tests.check_discriminators(conn, MS(testers), disc_range, mode, args.o))
		
	uut_failures = merge_failures_MS(uut_failures, tests.check_tdc(conn, MS(testers), "full", args.o))
	
	for att, mode in qdc_att_list.items():
		uut_failures = merge_failures_MS(uut_failures, tests.check_qdc(conn, MS(testers), att, mode, args.o))
		
	uut_failures = merge_failures_MS(uut_failures, tests.check_fetp_tres(conn, MS(testers), xxtp_att, args.o, fe_mode=True))
	uut_failures = merge_failures_MS(uut_failures, tests.check_fetp_eres(conn, MS(testers), xxtp_att, args.o, fe_mode=True))

	uut_failures = merge_failures_MS(uut_failures, tests.check_extp_tres(conn, MS(testers), xxtp_att, args.o, fe_mode=True))
	uut_failures = merge_failures_MS(uut_failures, tests.check_extp_eres(conn, MS(testers), xxtp_att, args.o, fe_mode=True))
		

	# ALDO tests
	read_temperature_probe1(args.o, "probe_1_before_aldo_scan")
	read_temperature_probe2(args.o, "probe_2_before_aldo_scan")

	conn.set_48V_power(True)
	for m, t in testers: t.enable_bias_voltage_load(True)
	uut_failures = merge_failures_MS(uut_failures, tests.check_aldo(conn, MS(testers), 1, (220+5.11)/5.11, args.o, fe_mode=True))

	read_temperature_probe1(args.o, "probe_1_after_aldo_scan")
	read_temperature_probe2(args.o, "probe_2_after_aldo_scan")

	for m, t in testers: t.enable_bias_voltage_load(False)
	uut_failures = merge_failures(uut_failures, tests.check_aldo_fe(conn, testers, args.o))
	conn.set_48V_power(False)

	detailed_results_file = open("%s/detailed_results.tsv" % args.o, "w")
	
	for m, failures in uut_failures.items():
		detailed_results_file.write("t%d\t%s\n" % (m, ("\t").join(failures)))

	detailed_results_file.close()
	

	print testers
	print uut_failures
	
	# Test sucessfully complete
	conn.set_uut_power(False)	


	return 0


def merge_failures(a, b):
	c = {}
	for k in a.keys():
		c[k] = a[k]
		if b.has_key(k):
			a[k] += b[k]
	
	return c


def disable_failed(testers, uut_failures):
	for m,t in testers:
		if uut_failures[m] != []:
			t.set_uut_power(False)

	result = [ (m,t) for m,t in testers if t.get_uut_power() ]
	return result

def merge_failures_MS(a, b):
	c = {}
	for m in a.keys():
		c[m] = a[m]
		for k in [0,1]:
			if b.has_key((m,k)):
				a[m] += [ "ASIC %d " % k + failure for failure in b[m,k] ]
	return c

def MS(testers):
		return sorted([ (m,a,t) for m,t in testers for a in [0,1] ])


def do_tester_check(conn):
	problems = False
	for (p,s,m),t in sorted(conn.get_testers().items()):
		tester_vin = t.get_tester_vin()
		
		if tester_vin < 1.6:
			print "Tester %d Vin %3.2f is LOW" % (m, tester_vin)
			problems = True
			
		if tester_vin > 2.5:			
			print "Tester %d Vin %3.2f is HIGH" % (m, tester_vin)
			problems = True
			
			
		# If the UUT has been disabled Vin should be ~0
		if t.get_uut_power() is False: continue
		
		uut_vin = t.get_uut_vin()
		
		if uut_vin < 1.6:
			print "Tester %d UUT Vin %3.2f is LOW" % (m, uut_vin)
			problems = True
			
		if uut_vin > 2.5:
			print "Tester %d UUT Vin %3.2f is HIGH" % (m, uut_vin)
			problems = True
	
	
	if problems:
		print "PROBLEMS FOUND IN TEST SYSTEM"
		exit(1)

	
if __name__ == '__main__':
	exit(main(sys.argv))
