#!/usr/bin/env python
# -*- coding: utf-8 -*-

from petsys import tester_controller, config, spi
from copy import deepcopy
import argparse
import math
import time



def main():
	parser = argparse.ArgumentParser(description='Set UUT power ON/OFF')
	parser.add_argument("--power", type=str, required=True, choices=["on", "off"], help="Set UUT power")
	args = parser.parse_args()

	conn = tester_controller.Connection()

	if args.power == "on":
		conn.set_uut_power(True)
	else:
		conn.set_uut_power(False)

	return 0



if __name__ == "__main__":
	main()

